### ISSUE TITLE
can i use it in vscode

### ISSUE THREAD

**Issue by denging3** [HaroldPutman/eslint-plugin-jsp#4]
I install eslint and eslint-plugin-jsp globally. And there is a '.eslintrc,json' file  in the project root directory . But it doesn't work.

**Comment by HaroldPutman** [comment]
I have not tried in vscode, but I assume it should work.  What does your .eslintrc.json contain. Did you add the special comments to your jsp code?

**Comment by denging3** [comment]
Thanks. It works well. I missed some configuration for vs.
Anyway, thank you very much.
